# https://starship.rs/

"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color_1)\
$directory\
[](fg:color_1 bg:color_2)\
$git_branch\
$git_status\
[](fg:color_2 bg:color_3)\
[$c\
$dotnet\
$golang\
$nodejs\
$rust$package](fg:color_brand bg:color_3)\
[](fg:color_3)\
$line_break\
$character"""

add_newline = true

## Theme ##

palette = 'super'

[palettes.super]
color_1 = "#252a36"
color_2 = "#34444f"
color_3 = "#425563"
color_brand = "#80e0a7"
color_error = "#ED4245"

## General ##

[character]
success_symbol = "[>](color_brand)"
error_symbol = "[x](color_error)"
vimcmd_symbol = "[<](bold green)"

[directory]
format = "[ $path ]($style)[$read_only]($style)"
style = "fg:color_brand bg:color_1"
read_only = "[ro]"
truncation_symbol = "…/"

## Git ##

[git_branch]
format = "[ $branch ]($style)"
style = "fg:color_brand bg:color_2"

[git_status]
format = "[\\[$all_status$ahead_behind\\] ]($style)"
style = "fg:color_brand bg:color_2"
ahead = ">"
behind = "<"
diverged = "<>"
renamed = "r"
deleted = "x"

## Languages ##

[c]
symbol = "C "
format = " $symbol$version "

[dotnet]
symbol = ".NET "
format = " $symbol$version "

[golang]
symbol = "go "
format = " $symbol$version "

[nodejs]
symbol = "nodejs "
format = " $symbol$version "

[rust]
symbol = "rs "
format = " $symbol$version "

[package]
format = "\\($version\\) "
